name: Email Notification

on: [push, pull_request]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Send email
      run: |
        sudo apt-get update && sudo apt-get install -y mailutils
        echo "Email notification content" | mail -s "Email notification subject" ce.nikpatel@gmail.com
